<div class="about">
  <h1>To whom it may concern (biology teachers at Wharton???)</h1>
  <p class="lead">I did <i>not</i> make this for people to cheat with, and if they do, it is out of my control. It was not what this website was made for. It was made to help people understand how DNA converts to mRNA, then to proteins. I am not responsible for misuse of this website.</p>
  <hr>
  <p>This website was made over the course of two hours on 1/10/2017 and runs on the <a href="https://www.github.com/EricRabil/steel-framework">Steel Framework</a> (also made by me)</p>
</div>
